export const HEADER_SETTINGS_TEST_ID = {
	HEADER: 'HEADER_TAG',
	LOGO: 'HEADER_LOGO',
	SEARCH_INPUT: 'HEADER_SEARCH_INPUT',
	BASE_LINK: 'HEADER_BASE_LINK',
	FAVORITES_LINK: 'HEADER_FAVORITES_LINK',
	CART_LINK: 'HEADER_CART_LINK',
	PROFILE_LINK: 'HEADER_PROFILE_LINK',
	GROUP_ICONS: 'HEADER_GROUP_ICONS',
}
